// <auto-generated />
using System;
using EDH.Infrastructure.Data.ApplicationDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EDH.Infrastructure.Data.Migrations
{
    [DbContext(typeof(EdhDbContext))]
    [Migration("20250815095924_MoneyAndQuantityValueObjects")]
    partial class MoneyAndQuantityValueObjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("EDH.Core.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("InventoryItem", (string)null);
                });

            modelBuilder.Entity("EDH.Core.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ItemCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("_sellingPriceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("SellingPrice");

                    b.HasKey("Id");

                    b.HasIndex("ItemCategoryId");

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("EDH.Core.Entities.ItemCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ItemCategory", (string)null);
                });

            modelBuilder.Entity("EDH.Core.Entities.ItemVariableCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("CostName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("_valueAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemVariableCost", (string)null);
                });

            modelBuilder.Entity("EDH.Core.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<decimal>("_totalAdjustmentAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("TotalAdjustment");

                    b.Property<decimal>("_totalProfitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("TotalProfit");

                    b.Property<decimal>("_totalValueAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("TotalValue");

                    b.Property<decimal>("_totalVariableCostsAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("TotalVariableCosts");

                    b.HasKey("Id");

                    b.ToTable("Sale", (string)null);
                });

            modelBuilder.Entity("EDH.Core.Entities.SaleLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("_adjustmentAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("Adjustment");

                    b.Property<decimal>("_profitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("Profit");

                    b.Property<decimal>("_subtotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("Subtotal");

                    b.Property<decimal>("_totalVariableCostsAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("TotalVariableCosts");

                    b.Property<decimal>("_unitPriceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("UnitPrice");

                    b.Property<decimal>("_unitVariableCostsAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("UnitVariableCosts");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleLine", (string)null);
                });

            modelBuilder.Entity("EDH.Core.Entities.InventoryItem", b =>
                {
                    b.HasOne("EDH.Core.Entities.Item", "Item")
                        .WithOne("Inventory")
                        .HasForeignKey("EDH.Core.Entities.InventoryItem", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EDH.Core.ValueObjects.Quantity", "AlertThreshold", b1 =>
                        {
                            b1.Property<int>("InventoryItemId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("AlertThreshold");

                            b1.HasKey("InventoryItemId");

                            b1.ToTable("InventoryItem");

                            b1.WithOwner()
                                .HasForeignKey("InventoryItemId");
                        });

                    b.OwnsOne("EDH.Core.ValueObjects.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<int>("InventoryItemId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(0)
                                .HasColumnName("Quantity");

                            b1.HasKey("InventoryItemId");

                            b1.ToTable("InventoryItem");

                            b1.WithOwner()
                                .HasForeignKey("InventoryItemId");
                        });

                    b.Navigation("AlertThreshold");

                    b.Navigation("Item");

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("EDH.Core.Entities.Item", b =>
                {
                    b.HasOne("EDH.Core.Entities.ItemCategory", "ItemCategory")
                        .WithMany("Items")
                        .HasForeignKey("ItemCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ItemCategory");
                });

            modelBuilder.Entity("EDH.Core.Entities.ItemVariableCost", b =>
                {
                    b.HasOne("EDH.Core.Entities.Item", "Item")
                        .WithMany("ItemVariableCosts")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("EDH.Core.Entities.SaleLine", b =>
                {
                    b.HasOne("EDH.Core.Entities.Item", "Item")
                        .WithMany("SaleLines")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EDH.Core.Entities.Sale", "Sale")
                        .WithMany("SaleLines")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EDH.Core.ValueObjects.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<int>("SaleLineId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Quantity");

                            b1.HasKey("SaleLineId");

                            b1.ToTable("SaleLine");

                            b1.WithOwner()
                                .HasForeignKey("SaleLineId");
                        });

                    b.Navigation("Item");

                    b.Navigation("Quantity")
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("EDH.Core.Entities.Item", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("ItemVariableCosts");

                    b.Navigation("SaleLines");
                });

            modelBuilder.Entity("EDH.Core.Entities.ItemCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EDH.Core.Entities.Sale", b =>
                {
                    b.Navigation("SaleLines");
                });
#pragma warning restore 612, 618
        }
    }
}
